# Generated by Django 3.0.5 on 2022-12-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzas', '0004_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='pizza_name',
            new_name='pizza',
        ),
    ]
